### ISSUE TITLE
why not check the right value is number or not like other functions

### ISSUE THREAD

**Issue by dabue** [api7/lua-resty-expr#15]
https://github.com/api7/lua-resty-expr/blob/677b7687b43cf25959ea2cb9b8e46d13d74464d3/lib/resty/expr/v1.lua#L73

**Comment by spacewander** [comment]
We don't need to `r_v` to be a number for equal comparison. The `r_v` can be string or nil or whatever.

**Comment by dabue** [comment]
but,  which return value is expected for this exp " "arg_age", "~=",  18 ", true or false? or don't allow this usage.

**Comment by spacewander** [comment]
@dabue 
I understand what you mean now. Yes, it is a bug, welcome to fix it!

**Comment by dabue** [comment]
I' ll fix it soon.
