### ISSUE TITLE
bug: `~~` and `~*` these three operation expressions need to be improved

### ISSUE THREAD

**Issue by Firstsawyou** [api7/lua-resty-expr#20]
1. When the operator is `~=` and the request parameter `name` is missing

```
=== TEST 30: the request parameter `name` is missing and the operator is `~=`

--- config
    location /t {
        content_by_lua_block {
            local expr = require("resty.expr.v1")
            local ex = expr.new({             
                {"arg_name", "~=", "jack"}            
            })

            ngx.say(ex:eval(ngx.var))
        }
    }
--- request
GET /t
--- response_body
true
```

In this test case, due to the lack of the `name` parameter in the acquisition, the expected result should be `false`, and the actual result is `true`.

2. When the operator is `~~` and the request parameter `name` is missing

```
=== TEST 31: the request parameter `name` is missing and the operator is `~~`
--- config
    location /t {
        content_by_lua_block {
            local expr = require("resty.expr.v1")
            local ex = expr.new({             
                {"arg_name", "~~", "[a-z]{1,4}"}            
            })

            ngx.say(ex:eval(ngx.var))
        }
    }
--- request
GET /t
--- response_body
true
```

In this test case, due to the lack of the `name` parameter in the acquisition, the expected result should be `false`, and the actual result is `true`.

3. When the operator is `~*` and the request parameter `name` is missing

```
=== TEST 32: the request parameter `name` is missing and the operator is `~*`
--- config
    location /t {
        content_by_lua_block {
            local expr = require("resty.expr.v1")
            local ex = expr.new({             
                {"arg_name", "~*", "[a-z]{1,4}"}
            })

            ngx.say(ex:eval(ngx.var))
        }
    }
--- request
GET /t
--- response_body
true
```

In this test case, due to the lack of the `name` parameter in the acquisition, the expected result should be `false`, and the actual result is `true`.

---------------------------

Therefore, when the operator is in these three cases, we should deal with the case where the value of the obtained variable is `nil`.

**Comment by spacewander** [comment]
I agree with you except the first case: should not `nil ~= "jack"` be true?

**Comment by Firstsawyou** [comment]
> I agree with you except the first case: should not `nil ~= "jack"` be true?

Yes, the result I got is true. I think `nil` should not be compared.

**Comment by Firstsawyou** [comment]
> I agree with you except the first case: should not `nil ~= "jack"` be true?

Yes, I thought about it. It is also a good choice to perform the `~=` operation when getting the variable value to be `nil`. I will submit a `PR` later to fix the two cases of `~~` and `~*`.
