### ISSUE TITLE
how about supporting an `or` operation among different expression

### ISSUE THREAD

**Issue by Gerrard-YNWA** [api7/lua-resty-expr#23]
Currently multiple expressions in rule params specified in `expr.new` use the `and` semantic in default. All the expressions should be matched at same time. Is there any consideration support the `or` semantic among different expressions?
Here is the example:
```
local ex = expr.new({
        {"user_type", "==", "admin"},
        {"device_type", "in", {"phone"}},
})
```
When we do `eval` method, any ctx table with an "admin" user_type or with a "phone" device_type will return true.

**Comment by spacewander** [comment]
There is a discussion: https://lists.apache.org/thread.html/r031b77f5b45d6d273ae66376209f155e28066824440348f41059bbac%40%3Cdev.apisix.apache.org%3E

**Comment by Gerrard-YNWA** [comment]
After reading the discussion. I have a question why not make `not` as a separate operator? 
 `and`, `or`, `not` are all logical operators.  
What about implement the `not` operator on the top layer like this?
```
[
    "not"
    [
        "and",                      
        ["arg_1","==","yaml"],
        [
            "or",
            ["arg_2","==","json"],
            [
                "not",
                ["arg_3",">",10]
            ]
        ]
    ]
]
``` 
means `not ( arg_1 == "yaml" and (arg_2 == "json" or not(arg_3 > 10)))`

In this way `not` can also represents the `!` operation to reverse the result.

**Comment by spacewander** [comment]
We already have `!`.
Implement yet another negative operator will add additional work load and more concepts to distinguish with.
