### ISSUE TITLE
The current release version v1.0.0 is not the latest code.

### ISSUE THREAD

**Issue by Firstsawyou** [api7/lua-resty-expr#24]
The `v1.0.0` version code lags behind the master branch code, there will be this bug:#20  #21 . 
We need a version of the latest master branch. By the way, update the [https://github.com/apache/apisix/blob/master/rockspec/apisix-master-0.rockspec#L59 ](https://github.com/apache/apisix/blob/master/rockspec/apisix-master-0.rockspec#L59) file in APISIX.

**Comment by spacewander** [comment]
PR is welcome!

**Comment by Firstsawyou** [comment]
We should first release a version of the master branch code, right?  Such as: `v1.1.0`

**Comment by spacewander** [comment]
Since there is only fix after release, `1.0.1` is enough.

**Comment by membphis** [comment]
vote for `1.1`, I think that is fine
