### ISSUE TITLE
How to implement operator like "<=" or ">="

### ISSUE THREAD

**Issue by tokers** [api7/lua-resty-expr#28]
Currently only `>` and `<` are supported, if we want to implement `<=` or `>=`, we may use the `!` operator to invert the result, but that's not totally equivalent with `<=` and `>=`, for instance:

```json
[
    ["arg_id", "!", ">", "14"]
]
```

And

```json
[
  ["arg_id", "<=", "14"]
]
```

Are not same.

When `arg_id` is missing, the first expression should always be deducted to `false`, but actually, we will get `true`.

**Comment by spacewander** [comment]
Maybe we can change the semantic for the undefined variable?
If the left value is nil/ngx.null, the expression is always evaluated as "false".

It will be a breaking change, but I think it is worthwhile for readability and consistency.

**Comment by spacewander** [comment]
For users who use `! >` to ensure undefined variable to return true, we can introduce an "undefined" operator. So

Previous
```
[
    ["arg_id", "!", ">", "14"]
]
```

==

Current
```
[
	"OR",
    ["arg_id", "!", ">", "14"],
	["arg_id", "undefined"]
]
```

**Comment by spacewander** [comment]
It seems we can use `"arg_id", "==", null` to achieve the same goal?

**Comment by spacewander** [comment]
I change my mind. Such breaking change is too subtle to detect.
Maybe we use:

```
[
  ["arg_id", "<", 14],
  ["arg_id", "==", 14]
]
```

to represent "<="?

**Comment by spacewander** [comment]
Or maybe we can implement "<=" directly as it is quite easy.

**Comment by tokers** [comment]
> Or maybe we can implement "<=" directly as it is quite easy.

I think this way is better.
