### ISSUE TITLE
not longer support for git protocol

### ISSUE THREAD

**Issue by findmark** [api7/lua-resty-expr#39]
Hi, my name is Mark, I just wrote an email to @membphis , and I think is better to open an issue here as well.

When I installing radixtree, a message shows as below. It looks like someone should replace git protocol with https in [here](https://luarocks.org/lua-resty-expr-1.3.0-0.rockspec), also take a look at [this](https://github.blog/2021-09-01-improving-git-protocol-security-github/)

> lua-resty-radixtree 2.8.1-0 depends on lua-resty-expr 1.3.0 (not installed)
> Installing https://luarocks.org/lua-resty-expr-1.3.0-0.rockspec
> fatal: remote error:
> The unauthenticated git protocol on port 9418 is no longer supported.
> Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

**Comment by findmark** [comment]
> Hi, my name is Mark, I just wrote an email to @membphis , and I think is better to open an issue here as well.
> 
> When I installing radixtree, a message shows as below. It looks like someone should replace git protocol with https in [here](https://luarocks.org/lua-resty-expr-1.3.0-0.rockspec), also take a look at [this](https://github.blog/2021-09-01-improving-git-protocol-security-github/)
> 
> > lua-resty-radixtree 2.8.1-0 depends on lua-resty-expr 1.3.0 (not installed)
> > Installing https://luarocks.org/lua-resty-expr-1.3.0-0.rockspec
> > fatal: remote error:
> > The unauthenticated git protocol on port 9418 is no longer supported.
> > Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

I just notice all repos under api7 are all base on git protocol. I may manually download the repos one by one for now.

**Comment by spacewander** [comment]
You need to upgrade luarocks to 3.8.0
See 
https://github.com/api7/lua-resty-expr/pull/38#pullrequestreview-915275967
https://github.com/apache/apisix/commit/5cde5ae0040f9fa7468dae12649276f07b0e9031
