### ISSUE TITLE
request help: Route vars regex match support case-insensitive

### ISSUE THREAD

**Issue by yangxikun** [api7/lua-resty-expr#4]
### Issue description

We want Route vars regex match support case-insensitive, such as match http_user_agent header value.

Is it possible add an `~*` operator to support case-insensitive? We are migrating from nginx.

And when will this lib be used in apisix?

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS:

**Comment by spacewander** [comment]
> Is it possible add an ~* operator to support case-insensitive? We are migrating from nginx.

PR is welcome!

> And when will this lib be used in apisix?

In a couple of days.

**Comment by membphis** [comment]
@yangxikun Do you want to contribute this feature?

**Comment by yangxikun** [comment]
I'm glad to make a PR in these two days.

**Comment by membphis** [comment]
@yangxikun  Many thanks for your contribution

**Comment by yangxikun** [comment]
We are waiting for this feature, which version of APISIX will support, and when?

**Comment by membphis** [comment]
I think we'll use this feature in APISIX soon.

you can create a new issue for discussing about this.
